# Generated by Django 5.2.8 on 2025-12-05 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_appp', '0002_orderss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='Userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
