# Generated by Django 5.2.8 on 2025-12-10 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_appp', '0003_alter_userss_userid_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_appp.menuu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_appp.userss')),
            ],
        ),
    ]
