# Generated by Django 5.2.8 on 2025-12-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_appp', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderss',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderss',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
