# Generated by Django 5.2.8 on 2025-12-16 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_appp', '0005_orderss_paid_orderss_stripe_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuu',
            name='food_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menuu',
            name='mood_tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
