# Generated by Django 5.2.8 on 2026-01-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_appp', '0006_menuu_food_tags_menuu_mood_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuu',
            name='DishType',
            field=models.CharField(default='Veg', max_length=10),
        ),
    ]
